import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import ts from 'typescript';
const out=new URL('../work/qa/',import.meta.url);await mkdir(out,{recursive:true});
for(const file of ['ratings','cards','game']){const input=await readFile(new URL('../lib/'+file+'.ts',import.meta.url),'utf8');await writeFile(new URL(file+'.mjs',out),ts.transpileModule(input,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText.replace("'./cards'","'./cards.mjs'").replace("'./ratings'","'./ratings.mjs'"));}
const {classify,beats,legalMoves}=await import(new URL('cards.mjs',out));
const {newRoom,applyAction,publicRoom,bid,play,settle,tick}=await import(new URL('game.mjs',out));
const cards=(...ranks)=>{const counts={};return ranks.map(r=>(r-3)*4+(counts[r]=(counts[r]||0)+1)-1)};
const cases=[[[3],'single'],[[3,3],'pair'],[[3,3,3],'triple'],[[3,3,3,4],'triple-single'],[[3,3,3,4,4],'triple-pair'],[[3,4,5,6,7],'straight'],[[3,3,4,4,5,5],'pairs'],[[3,3,3,4,4,4],'triples'],[[3,3,3,4,4,4,5,6],'plane-single'],[[3,3,3,4,4,4,5,5,6,6],'plane-pair'],[[3,3,3,3,4,4],'four-single'],[[3,3,3,3,4,4,5,5],'four-pair'],[[3,3,3,3],'bomb']];
for(const [rs,kind]of cases)assert.equal(classify(cards(...rs))?.kind,kind);
assert.equal(classify([52,53]).kind,'rocket');assert.equal(classify(cards(11,12,13,14,15)),null);assert.equal(classify([0,0]),null);assert.equal(classify([...cards(3,3,3,4,4,4),52,53]),null);assert.equal(classify(cards(3,3,3,3,4,4,4,5)),null);
assert.ok(beats(classify(cards(3,3,3,3)),classify(cards(14,14))));assert.ok(!beats(classify(cards(14,14,14,14)),classify([52,53])));assert.ok(!beats(classify(cards(4,5,6,7,8,9)),classify(cards(3,4,5,6,7))));
const make=(mode='team',extra={})=>{const r=newRoom('TESTROOM','host',{name:'测试房主',title:'验证',mode,rounds:1,boards:2,seconds:120,format:'fixed',...extra});applyAction(r,'host',{type:'bots'});applyAction(r,'host',{type:'start'});return r;};
for(let lord=1;lord<=3;lord++){const r=make();assert.deepEqual(r.tables[0].bottom,r.tables[1].bottom);for(let s=0;s<4;s++)assert.deepEqual(r.tables[0].hands[s],r.tables[1].hands[s+4]);const t=r.tables[0];for(let s=1;s<=lord;s++)bid(r,t,s,s===lord?3:0,0);assert.equal(t.idle,(lord+2)%4);assert.equal(t.hands[lord].length,20);assert.equal(new Set(Object.values(t.hands).flat()).size,54);assert.equal(t.active.length,3);const own=publicRoom(r,'host',0),guest=publicRoom(r,'guest',0);assert.equal(own.tables[1].phase,'hidden');assert.deepEqual(guest.tables[0].hand,[]);assert.equal(guest.players[0].session,undefined);assert.equal(guest.owner,undefined);assert.throws(()=>applyAction(r,'guest',{type:'next'}));assert.throws(()=>play(r,t,lord,[99],0));}
for(let seed=0;seed<12;seed++){const r=make(seed%2?'individual':'team',{rounds:2,boards:2});r.players.forEach(p=>p.bot=false);let steps=0,now=Date.now();while(r.status!=='finished'&&steps++<3000){if(r.status==='board_end'||r.status==='round_end'){applyAction(r,'host',{type:'next'},now);continue;}assert.equal(r.status,'playing');now+=100;for(const t of r.tables){if(t.phase==='bid')bid(r,t,t.turn,t.bid===0?(t.id?1:3):0,now);else if(t.phase==='play')play(r,t,t.turn,legalMoves(t.hands[t.turn],t.last?.pattern||null)[0]||[],now);}for(const t of r.tables){for(const hand of Object.values(t.hands))assert.equal(new Set(hand).size,hand.length);if(t.phase==='play')for(const move of legalMoves(t.hands[t.turn],t.last?.pattern||null)){assert.ok(classify(move));assert.ok(move.every(c=>t.hands[t.turn].includes(c)));}}}assert.equal(r.status,'finished');assert.equal(r.roundResults.length,2);if(r.settings.mode==='individual')assert.equal(r.totals.reduce((a,b)=>a+b,0),0);else for(const h of r.history)assert.ok(Math.max(...h.delta)<=12);}
const score=(a,b,extra={})=>{const r=make('team',extra);for(const [i,t]of r.tables.entries()){t.phase='done';t.winner=i?4:0;t.points=i?b:a;}settle(r);return r;};
assert.deepEqual(score(30,1).scores,[12,0]);assert.equal(score(12,0,{boards:2}).status,'board_end');assert.equal(score(13,0,{boards:2}).status,'board_end');
const overtime=score(0,0,{boards:1,format:'best'});assert.equal(overtime.status,'board_end');assert.equal(score(0,0,{boards:1}).status,'board_end');
const spring=make('individual',{boards:1});const st=spring.tables[0];bid(spring,st,0,3,0);st.hands[0]=[0];play(spring,st,0,[0],0);assert.equal(st.spring,true);assert.equal(st.points,6);assert.deepEqual(spring.totals,[12,-6,-6]);
console.log('PASS: card patterns, invalid moves, duplicate deals, partner transfers, privacy, scores, spring, overtime, 12 complete simulated matches.');
if(process.argv.includes('--api')){
 const base=process.env.TEST_URL||'http://localhost:3000';
 const client=()=>({cookie:'',async req(path,body){const res=await fetch(base+path,{method:body?'POST':'GET',headers:{...(this.cookie?{cookie:this.cookie}:{}),...(body?{'Content-Type':'application/json','Origin':base}: {})},body:body?JSON.stringify(body):undefined});if(res.headers.get('set-cookie'))this.cookie=res.headers.get('set-cookie').split(';')[0];return {status:res.status,data:await res.json()};}});
 for(const mode of ['individual','team']){const clients=Array.from({length:mode==='team'?8:3},client),host=clients[0];const created=await host.req('/api/rooms',{name:'联机房主',title:'自动联机验证',mode,rounds:2,boards:2,seconds:120,format:'fixed'});assert.equal(created.status,201);const path='/api/rooms/'+created.data.code;
  const outsider=client();assert.equal((await outsider.req(path,{type:'start'})).status,400);
  const race=await Promise.all([clients[1].req(path,{type:'join',name:'选手1',seat:1}),outsider.req(path,{type:'join',name:'争位',seat:1})]);assert.deepEqual(race.map(r=>r.status).sort(),[200,400]);if(race[0].status!==200){await outsider.req(path,{type:'leave'});assert.equal((await clients[1].req(path,{type:'join',name:'选手1',seat:1})).status,200);}
  for(let i=2;i<clients.length;i++)assert.equal((await clients[i].req(path,{type:'join',name:'选手'+i,seat:i})).status,200);
  for(let i=1;i<clients.length;i++)await clients[i].req(path,{type:'ready'});
  let result=await host.req(path,{type:'start'});assert.equal(result.status,200);let v=result.data,steps=0;
  while(v.status!=='finished'&&steps++<2500){if(v.status==='board_end'||v.status==='round_end'){v=(await host.req(path,{type:'next',expected:`${v.round}:${v.board}:${v.status}`})).data;continue;}assert.equal(v.status,'playing');
   for(let table=0;table<(mode==='team'?2:1);table++){const seat0=table*4;const tableView=(await clients[seat0].req(path)).data.tables[table];if(tableView.phase==='done')continue;const c=clients[tableView.turn],view=(await c.req(path)).data,t=view.tables[table];assert.ok(t.hand.length>0);if(mode==='team')assert.equal(view.tables[1-table].phase,'hidden');assert.equal(JSON.stringify(view).includes('session'),false);const action={type:t.phase==='bid'?'bid':'play',expected:`${view.round}:${view.board}:${t.log.length}:${t.turn}`,...(t.phase==='bid'?{value:t.bid===0?(table?1:3):0}:{cards:legalMoves(t.hand,t.last?.pattern||null)[0]||[]})};const rr=await c.req(path,action);assert.equal(rr.status,200,JSON.stringify(rr.data));if(steps===1){const again=await c.req(path,action);assert.equal(again.status,409);} }
   v=(await host.req(path)).data;
  }
  assert.equal(v.status,'finished');assert.equal(v.roundResults.length,2);assert.ok(v.history.length>=4);assert.equal((await host.req(path)).data.me,v.me);console.log(`PASS API: ${mode}, ${clients.length} isolated sessions, seat collision, authorization, stale moves, refresh, 2 rounds × 2 deals.`);
 }
}
